### ISSUE TITLE
Provide recommended barebones CSS?

### ISSUE THREAD

**Issue by hoffa** [hoffa/pt#10]
e.g.

```css
body {
  font-family: system-ui, sans-serif;
  line-height: 1.5;
  max-width: 40em;
  margin: 0 auto;
  padding: 0 1em;
}
```
